🚀 2단계 - HTTP 서버 구현하기
next-step/java-http pull request #14
Opened 2024-07-08 07:04 UTC by jwoo-o

안녕하세요 동철님
2단계 HTTP 서버 구현하기 리뷰 요청드립니다.

나눠서 커밋했어야됬는데 1,2,3를 한번에 작성해버려 통커밋으로 보내버렸네요

다음번엔 나눠서 커밋하도록 하겠습니다.

2024-07-09 00:36 UTC, sah3122 requested changes
미션 구현 잘해주셨네요 👍 
다음 미션을 진행하기 전 사소한 코멘트 몇가지 남겨두었는데 확인 부탁드려요 😄

2024-07-09 00:36 UTC, sah3122 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                "Content-Type: " + ContentType.from(requestLine.getExtension()).getValue() + " ",
Request Line을 활용하여 ContentType 잘 가져와 주셨네요 👍

2024-07-09 00:36 UTC, sah3122 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
세번째 미션을 위해 추가해주신 코드인것 같습니다. 
실제 http 서버를 구현한다고 가정하고, extentions이 없는 경우 HTML로 반환하는 코드와 같이 현시점에서 불필요한 코드는 제거하는것이 좋을것 같아요 😄 
더 나아가 지원하지 않는 확장자 또는 404 응답을 주는것도 좋을것 같네요 😄

2024-07-09 00:36 UTC, sah3122 commented on tomcat/src/main/java/org/apache/coyote/http11/ContentType.java
> +public enum ContentType {
ContentType 정의 👍

2024-07-09 00:36 UTC, sah3122 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                responseBody);
response를 생성하는 로직을 분리 및 상세하게 구현 해보는것도 좋을것 같습니다 😄

2024-07-09 00:36 UTC, sah3122 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpPath.java
> +    private HttpPath(String path, Query query) {
생성자 파라미터를 수정하기 보단 생성자를 추가하는 방향으로 접근하는건 어떨까요 ? 
다양한 생성자를 정의해보세요 😄

2024-07-09 00:36 UTC, sah3122 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            }
Response를 생성한 이후 비즈니스 로직이 수행되기 보단, 비즈니스 로직이 우선적으로 실행되는 구조가 자연스러울것 같습니다 😄

2024-07-09 00:36 UTC, sah3122 commented on tomcat/src/test/java/org/apache/coyote/http11/RequestLineTest.java
> +class RequestLineTest {
상세한 테스트 코드 작성 👍

2024-07-09 03:40 UTC, jwoo-o commented on tomcat/src/main/java/org/apache/coyote/http11/HttpPath.java
> +    private HttpPath(String path, Query query) {
수정없이 추가하는 방향이 좋을거 같습니다.
적용하도록 하겠습니다.

2024-07-10 02:02 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
깔끔하게 구현 잘해주셔서 크게 코멘트 드릴 부분이 없네요 😄 
프로세서의 크기가 커지고 있는데, 리팩터링 미션에서 구조를 변경해주시면 될것 같습니다 ! 
다음 미션도 화이팅 하세요 💯

2024-07-10 02:02 UTC, sah3122 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            Response response = getResponseBody(path)
Response 응답 정의 👍

2024-07-10 02:02 UTC, merged