🚀 1단계 - TDD 실습
next-step/java-http pull request #22
Opened 2024-07-09 05:47 UTC by gutenLEE

안녕하세요 리뷰어님!
리뷰 잘 부탁드리겠습니다!

이번 미션은 책임 분리에 집중해서 코드를 개선해봤습니다!

2024-07-09 15:10 UTC, shared-moon requested changes
안녕하세요!
1단계 미션 잘 진행 해 주셨네요 :)
피드백을 좀 남겨 뒀는데, 다음 미션 진행 전 확인해보면 좋을 것 같아요~
확인 후 리뷰 재요청 부탁드려요!

2024-07-09 15:10 UTC, cogito90 commented on study/src/test/java/study/FileTest.java
> +        final String currentDirectory = new File("").getAbsolutePath();
👍 
`getResource()` 를 통한 방법도 찾아보시면 좋을 것 같아요 :)

2024-07-09 15:10 UTC, cogito90 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            if (requestLine.pathEndsWith("/index.html")) {
`.html` 로 들어오는 녀석들은 전부 리소스를 리턴해줘야 할 것 같은데요, 공통 로직을 활용할 수 있도록 해주는 건 어떨까요 ?

2024-07-09 15:10 UTC, cogito90 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                        "Content-Type: text/html;charset=utf-8 ",
content type은 매번 달라질 수 있을 것 같아요 ~

2024-07-09 15:10 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                        "Content-Length: 5564 ", // 운영체제 환경에 따라 다른 값이 나올 수 있음. 자신의 개발 환경에 맞춰 수정할 것.
요것도 상수로 넣기보단 실제 데이터의 사이즈를 넣어줘야 하지 않을까요 ?

2024-07-09 15:10 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/Path.java
> +        this.path = values[0];
인덱스는 상수로 정의해보면 어떨까요 ?

2024-07-09 15:10 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/Path.java
> +    public Map<String, Object> getQueryParamMap() {
위에 파라미터가 없는 경우엔 queryParam이 null인 상태로 있을 것 같은데 여기서 NPE가 나지 않을까요 ?

2024-07-09 15:10 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/QueryParam.java
> +    private static String[] parseKeyValue(String query) {
위에서 바로 Entry로 감싸는데 여기서 Entry를 리턴해주는건 어떨까요 ?

2024-07-09 15:10 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    public String getRequestLine(InputStream is) {
안쓰이는 메서드 같네요 ~ 안쓰는 메서드는 바로바로 지워주세요 ~

2024-07-09 15:10 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/RequestParser.java
> +        final var br = new BufferedReader(new InputStreamReader(is, charset));
사용된 BufferedReader와 하위에 리더들은 닫아줘야 할 것 같아요 ~

2024-07-09 15:10 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/RequestParser.java
> +        if (!lines.isEmpty()) {
requestLine 만 필요하신거면 굳이 다 읽은다음에 처음꺼를 가져올 필요가 있을까요 ?

2024-07-10 09:55 UTC, gutenLEE commented on study/src/test/java/study/FileTest.java
> +        URL resource = getClass().getClassLoader().getResource(fileName);
`getResource()`는 어떻게 파일 이름만으로 파일 찾고 로딩하는지 내부 구현 코드를 확인해봤습니다. 
리소스를 찾을때까지 `PlatformClassLoader`,  `BootLoader`, 어플리케이션 로더 구현체들을 
순서대로 순회하면서 로더가 갖고 있는 클래스 패스 정보로 탐색하는 듯하네요!

2024-07-10 09:55 UTC, gutenLEE commented on tomcat/src/main/java/org/apache/coyote/http11/Path.java
>      }
쿼리 스트링이 없을경우 `Map.of()`, 빈 Map을  를 반환하도록 했습니다!

2024-07-10 09:55 UTC, gutenLEE commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                Path filePath = FileLoader.read("static/index.html");
> .html 로 들어오는 녀석들은 전부 리소스를 리턴해줘야 할 것 같은데요, 공통 로직을 활용할 수 있도록 해주는 건 어떨까요 ?

공통 로직을 파일을 로딩하는 로직으로 이해했는데 리뷰어님 의도와 일치할까요?!

2024-07-10 09:58 UTC, gutenLEE commented on tomcat/src/main/java/org/apache/coyote/http11/Path.java
>      }
쿼리 파라미터가 없을 경우 `getQueryParamMap()` NPE 가 터지는 것 보다
역직렬화된 쿼리 파라미터에 key로 조회할 때 null을 반환받는 것이 자연스럽다 생각하여 이렇게 변경해봤습니다!

2024-07-10 10:25 UTC, gutenLEE commented on tomcat/src/main/java/org/apache/coyote/http11/Response.java
> +        sb.append("\r\n");
CRLF 를 사용한 이유는 `System.lineSepeator()`를 사용해도 테스트가 깨져서입니다ㅜㅜ

2024-07-10 15:52 UTC, shared-moon approved these changes
피드백 반영 잘 해주셨네요 :)
PR은 바로 머지하도록 하겠습니다.
고생 많으셨어요!

2024-07-10 15:52 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                Path filePath = FileLoader.read("static/index.html");
👍  Response 만드는것까지 고려해서 공통화시켜보면 더 좋을 것 같아요!

2024-07-10 15:52 UTC, merged