Step2 http 서버 구현하기
next-step/java-http pull request #34
Opened 2024-07-11 14:35 UTC by newvelop

- 1번 과제에 있었던 path를 별도 클래스로 처리
- container와 별도 핸들러를 추가하여 http 요청을 종류별로 처리

2024-07-12 09:26 UTC, catsbi requested changes
현오님 2단계 미션 구현 꼼꼼하게 잘 해주셨어요 👍 
몇 가지 피드백 남겨드렸으니 확인해보시면 좋을 것 같고, 추가적으로 현재 요구사항3번 쿼리스트링 출력하는게 제대로 안되고 정적 리소스 접근에 대한 예외가 계속 콘솔 로그에 찍히고 있는데, 경로를 잘 못찾아주고있는 것 같으니 확인해주시면 좋을 것 같습니다!. 

확인 후 다시 리뷰요청 부탁드려요

2024-07-12 09:26 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/domain/Path.java
> +        if (pathStrs.length == 2) {
2가 뭘 의미하는지 파악할 수 있게 상수로 만들어 네이밍을 해주면 가독성이 높아질 것 같네요!

2024-07-12 09:26 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/domain/Path.java
> +        String[] pathStrs = path.split("\\?");
split함수도 사실 내부적으로는 Pattern 객체를 생성하는데 이 Pattern 객체의 생성비용은 결코 낮은편이 아니라서, 사용빈도에 따라서는 별도의 정적 객체로 만들어서 성능을 챙길 수 있습니다 ㅎㅎ

2024-07-12 09:26 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/domain/Path.java
> +                .collect(Collectors.toMap(e -> e[0], e -> e[1]));
여기도 매직넘버와 리터럴을 좀 더 가독성 좋게 리팩토링해보면 좋을 것 같네요!

2024-07-12 09:26 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/domain/Resource.java
> +public class Resource {
Request, Response, Resource 라는 클래스 이름은 무슨 책임을 가지는지에 대한 시그니처가 너무 포괄적인것 같아요. 
좀 더 명확한 네이밍으로 가봐도 좋을 것 같네요(ex: HttpRequest, HttpServletRequest, ...)

2024-07-12 09:26 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/domain/Response.java
> +        String fileStr = new String(Files.readAllBytes(file.toPath()));
readAllBytes는 실무에서 사용할때 위험한 부분이 있는데, 그 부분에 대해서도 고민해보면 좋을 것 같습니다

2024-07-12 09:26 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/handler/LoginRequestHandler.java
> +    private void checkUser(Map<String, String> queryParams) {
이 로직도 차후 분리를 고려해보면 좋을 것 같네요 ㅎㅎ

2024-07-12 09:26 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/handler/LoginRequestHandler.java
> +        findByAccount(account).ifPresent(user -> System.out.println(user));
System.out을 사용하기보단 Logger를 활용해보면 어떨까요?

2024-07-12 09:26 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/handler/RequestHandler.java
> +    boolean isMatchPathPattern(String path);
- 반환타입은 Response로 지정하면 유연성이 떨어질 수 있으니 당장은 몰라도 여유가 되실 때 좀 더 확장성있는 설계를 고민해보면 좋을 것 같습니다 :) 
- isMatchPathPattern은 좀 더 추상적인 이름으로도 핸들링이 될 수 있을 것 같아요. 지금은 이 핸들러가 실행하기 위한 조건으로 오직 path만 고려할 수 있는 함수가 기능 정의되있다보니 이 역시 너무 좁은 범위의 책임만 할 수 있을 것 같아요.

2024-07-12 09:26 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/handler/RequestHandlerContainer.java
> +        }
Stream API를 통해 indent를 줄여볼수도 있을 것 같네요!

그리고 현재는 처음 찾는 핸들러가아니라 분기문에 맞는 조건을 가진 핸들러가 하나 이상일 경우도고려되면 좋을 것 같네요

2024-07-17 02:41 UTC, newvelop commented
일단 npe가 계속 나는 이유는 
![image](https://github.com/user-attachments/assets/850b141b-3e15-4118-a8ea-4436e34866f4)

favicon.ico를 계속 요청에서 찾고있는데 해당 파일이 없어서 나고있습니다. 정상동작인거같은데 이를 예외처리하면 될까요?

2024-07-17 02:51 UTC, newvelop commented on tomcat/src/main/java/camp/nextstep/http/domain/Path.java
> +        String[] pathStrs = path.split("\\?");
사용 빈도수가 높지 않다고 판단되어 객체생성비용보다는 가독성을 따라서 간 부분이긴합니다. 일반적으로 split을 많이 사용하긴 하니까요 ㅎㅎ 트래픽 처리에 비용이 꽤 높다고 생각하여 수정하겠습니다~

2024-07-17 02:52 UTC, newvelop commented on tomcat/src/main/java/camp/nextstep/http/domain/Resource.java
> +public class Resource {
과제 자체가 RequestLine으로 진행되다 보니, HTTPRequest라고 진행하기 보단 Request와 Response로 진행한 부분이긴 합니다. Http를 붙여서 해당 프로토콜의 요청을 처리한다 정도로 진행하겠습니다 ㅎㅎ

2024-07-17 03:04 UTC, newvelop commented on tomcat/src/main/java/camp/nextstep/http/handler/LoginRequestHandler.java
> +    private void checkUser(Map<String, String> queryParams) {
유저를 찾는 역할은 repository에있고, 이 조회한 유저를 바탕으로 비교하는건 핸들러가 역할이라고 생각되는데요 혹시 분리해야되는 이유가 있을까요?

2024-07-17 03:08 UTC, newvelop commented on tomcat/src/main/java/camp/nextstep/http/handler/RequestHandler.java
> +    boolean isMatchPathPattern(String path);
isMatchPathPattern 는 처리해야될 경로만 바탕으로 적합한 핸들러를 뽑아서 처리할 목적으로 설계된 메소드라서 적합한 역할을 지니고있다고 생각하는데요, 혹시 경로말고 어떤 요소가 더 추가될수있을까요? 그부분이 명확하다면 그부분을 반영할수있을거같습니다~

추가적으로 Response는 현재 string으로만 내려갈수있을거같아서 해당 클래스로만 내리고있고, 파일 등의 요소가 고려된다면 상위 인터페이스를 하나 만들면될거같습니다. 혹시 이부분에 피드백을 주신것일지 아니면 다른관점에서 주신것일지 궁금합니다!

2024-07-17 03:14 UTC, newvelop commented on tomcat/src/main/java/camp/nextstep/http/handler/RequestHandlerContainer.java
> +        }
현재로썬 핸들러 하나만 동작을 하게 하려고 설계한 부분이긴한데요 혹시 파일/로그인/해당 경로에 맞는 요청처리를 하는 객체 말고 추가적으로 필요한게있을까요? 경로가 추가되면 별도의 객체를 생성할예정이었습니다. 

여러개가 한번에 처리되는 핸들러를 고민한적이없어서 이부분의 의견을 알려주시면감사하겠습니다~

ps. stream을 통한 변경은 완료하였습니다~

2024-07-17 04:57 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/domain/Path.java
> +        String[] pathStrs = path.split("\\?");
네네 늘 split을 사용하지 않는건 아니고 사용 빈도수나 필요에 따라 반영하시면 될 것 같습니다!

2024-07-17 05:15 UTC, catsbi approved these changes
현오님 피드백 반영 잘 해주셨습니다! 
피드백에 대해 고민해보면 좋을 주제로 댓글을 달아주셔서 답변 달아놨고, 
다른 큰 특이사항은 없어 머지하도록 하겠습니다. 다음 단계 진행해주세요!

2024-07-17 05:15 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/handler/LoginRequestHandler.java
> +    private void checkUser(Map<String, String> queryParams) {
유저를 저장소에 보관및 반환하는건 repository가 맞습니다! 제가 말한 분리는 음 핸들러와 레파지토리 사이에 서비스 레이어를 차후 고려해봐야 할 것 같다는 의미였습니다. 핸들러는 서블릿이라고 볼 수 있는데 이 서블릿은 비즈니스 로직보단 외부와의 연결 및 요청정보 전달 및 응답정보 반환하는 역할이 주된 목적이니까요 ㅎㅎ

2024-07-17 05:15 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/handler/RequestHandler.java
> +    boolean isMatchPathPattern(String path);
제가 생각하는 부분들을 언급하는건 그 부분에 대해서만 추가가될 것이고 저는 이보다는 좀 더 범용적인 이름을 통한 확장성의 고려를 피드백드린것입니다.  스프링의 DI container도 타입 검색 > 이름 검색 > 프라이머리 빈 검색 > Priority 애노테이션 순서를 가지는 것처럼요 ㅎㅎ 

그리고 반환타입도 view 경로일수도, json자체일수도, 특정 객체일수도, ModelAndView타입처럼 정의된 View DTO 로도 확장해볼 수 있으니 타입을 너무 하나로 굳힐 필요는 없다는 말이였습니다. 

우리가 정말 새로운 기능을 만들고 어떻게 확장될지도 모르는 상황이라면 굳이 억지로 확장성을 고려해서 오버 엔지니어링을 할 필요는 없지만, 현재 우리는 수레바퀴를 재발명하면서 가는 길이기에 어느 확장성을 고려해야하는지 알고 있으니까 너무 단계를 지킨다고 알고 있는 확장성을 고려하지 않을 필요는 없다고 생각해요 :)

2024-07-17 05:15 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/handler/RequestHandlerContainer.java
> +        }
아하 제 피드백은 하나 이상의 핸들러가 실행되야한다는 내용이라기보다는 컨트롤러에 지정된 path는 같되 각 함수별 path는 다를 수 있는걸 생각했는데, 잘 생각해보니 어짜피 path에 맞는 컨트롤러 지정시점에 pull path를 만들어서 등록해주면 해결되는 문제라 indent 축소 피드백만 고려해주시면 될 것 같습니다!

2024-07-17 05:15 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/handler/HttpRequestHandlerContainer.java
> +    public HttpRequestHandlerContainer() {
이런 구체화에 대한 의존을 추상화하기위해 Config 계층을 하나 만드는것도 괜찮을 것 같아요 ㅎㅎ 나중에 DI 고도화를 할 때 분리하기도 더 편할꺼구요 ㅎㅎ

2024-07-17 05:15 UTC, catsbi commented on tomcat/src/main/java/camp/nextstep/http/handler/HttpRequestHandlerContainer.java
> +        );
개인적으로 이런식으로 get(0)을 한다면 왜 그래도 되는지에 대한 주석은 작성하는걸 권장드려요

2024-07-17 05:15 UTC, merged