🚀 2단계 - HTTP 서버 구현하기
next-step/java-http pull request #37
Opened 2024-07-12 07:48 UTC by gutenLEE

### 질문

1. **커밋 단위**
   요구사항을 정리하지 않고 개발하니 커밋 단위도 이상하고, 생각나는대로 개발하는 악습관이 들어 리셋하고 다시 코딩했습니다 !
요구사항별로 작업하고 커밋 단위를 나누니 개인적으로 깔끔해졌다고 느꼈는데, 리뷰어님에게도 괜찮은가요?

2. **프론트 컨트롤러**
   요청을 처리하는 로직을 계속 리팩토링하다 보니 프론트 컨트롤러 패턴이 왜 생겨났는지 이해하게 되었습니다. 
개선할 부분들이 더 보이지만, 리뷰를 먼저 받고 싶어 PR 요청드립니다.

3. **예외 처리**
   예외 핸들링 부분이 잘 안되고 있습니다ㅠㅠ 
예외 처리도 일관성 있게 각 레이어별로 통일이 필요하다고 느꼈지만, 점진적으로 개선해보겠습니다.

4. **학습 방법**
   제가 먼저 개발 후 막히는 부분이 있으면 톰캣 코드를 참고하는데, 
톰캣 코드를 먼저 보고 구조를 파악한 다음 최대한 흉내 내보는 방식이 더 적합할까요?

2024-07-12 07:52 UTC, gutenLEE commented on tomcat/src/main/java/org/apache/coyote/http11/RequestParser.java
여기서 `try-with-resources` 구문을 사용하면 Socket스트림이 닫히게되어
`Http11Processor` 에서 Socket closed 예외가 발생합니다! 😭

또 특이한 것은 InputStream뿐만 아니라 SocketOutputStream도 닫히네요.. 
학습테스트로 재현이 안 되서 더 학습이 필요할 것 같습니다!

검색해보니 close가 전파되지 않게 스트림을 래핑하는 방법이 있던데
아직 찾지 못하였습니다

2024-07-14 06:43 UTC, shared-moon commented
>커밋 단위
>요구사항을 정리하지 않고 개발하니 커밋 단위도 이상하고, 생각나는대로 개발하는 악습관이 들어 리셋하고 다시 코딩했습니다 !
>요구사항별로 작업하고 커밋 단위를 나누니 개인적으로 깔끔해졌다고 느꼈는데, 리뷰어님에게도 괜찮은가요?

기능 구현 목록을 정리하고 목록 별로 커밋 나누는 건 좋은 시도라고 생각합니다! 가끔 나누기 힘들때도 있긴 한데 .. 커밋 단위는 최대한 작게 나누는게 히스토리 파악할때도 용이해요!
저도 물론 괜찮긴 한데, 보통은 PR 전체 변경사항을 보기때문에 크게 차이는 없습니다!

>학습 방법
>저는 먼저 개발 후 막히는 부분이 있으면 톰캣 코드를 참고하는데,
>톰캣 코드를 먼저 보고 구조를 파악한 다음 최대한 흉내 내보는 방식이 더 적합할까요?
>물론 개인의 학습 방법의 문제지만 리뷰어님은 어떤 방식으로 학습하셨는지 궁금합니다! 😀

레퍼런스를 보고 따라 하는것도 물론 학습 방법의 하나지만, 이 미션 진행하면서는 그 구조를 생각하는 힘을 기르는 것에도 목적이 있다고 생각하기 때문에 개인적으로는 먼저 해보시고 막히면 한번 찾아본다던지, 막히면 막히는 대로 방법을 만들어보는게 더 좋다고 생각해요!

제 경우는 이 학습과정의 얘기는 아니긴 한데, 외부 라이브러리 없이 필요한 기능들을 만들어서 썼을 때 (json 파싱, 커넥션 풀링 등등) 공부가 가장 많이 됐었고, 그 다음에 각각의 차이를 비교해보면서 많이 배웠었어요. 물론, 말씀하신대로 본인한테 맞는 공부 방법을 찾는게 가장 중요하다고 생각합니다 :)

2024-07-14 07:06 UTC, shared-moon requested changes
안녕하세요!
2단계 미션 잘 진행 해 주셨네요 :)
피드백을 좀 남겨 뒀는데, 이번 단계에서 한번 처리하고 넘어가면 좋을 것 같아요
확인 후 리뷰 재요청 부탁드려요!
혹시 이해 안가는 부분이 있으시면 언제든지 DM 주세요 ~

2024-07-14 07:06 UTC, cogito90 commented on tomcat/src/main/java/org/apache/coyote/http11/RequestParser.java
데이터를 읽는것과 파싱하는것의 책임을 분리하시면 될 것 같아요 ~
그리고 닫는건 가장 상위 레이어에서 책임을 지면 될 것 같습니다

2024-07-14 07:06 UTC, cogito90 commented on https/index.http
> +### GET /
👍

2024-07-14 07:06 UTC, cogito90 commented on tomcat/src/main/java/camp/nextstep/UserController.java
> +    public static ViewModel findUser(Map<String, Object> queryParamMap) {
요건 왜 static으로 하셨을까요 ?

2024-07-14 07:06 UTC, cogito90 commented on tomcat/src/main/java/org/apache/coyote/http11/ApplicationRequestHandler.java
> +        if (requestLine.getPath().startsWith("/login")) {
쿼리 파라미터 부분을 빼고 path를 잘라서 equasl로 비교해야하지 않을까요 ?
만약 `/login/v2` 이런식의 path가 있다면 같은 분기를 탈 것 같아요

2024-07-14 07:06 UTC, cogito90 commented on tomcat/src/main/java/org/apache/coyote/http11/ContentType.java
> +        if (path.endsWith(".css"))
지원가능한 타입이 늘어 날 때마다 여길 신경써야 할 것 같은데요, stream().filter를 이용해보면 어떨까요 ?

2024-07-14 07:06 UTC, cogito90 commented on tomcat/src/main/java/org/apache/coyote/http11/FileLoader.java
> +    private static final Pattern FILE_EXTENSION_PATTERN = Pattern.compile(".+(\\.html|.css|.js)$");
여기도 지원 가능한 타입이 늘어날 때마다 신경써줘야 할 것 같은데, 공통화시킬 수 없을까요 ?

2024-07-14 07:06 UTC, cogito90 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final var requestLine = RequestParser.parse(inputStream, StandardCharsets.UTF_8);
깔끔하네요 👍

2024-07-14 07:06 UTC, cogito90 commented on tomcat/src/main/java/org/apache/coyote/http11/ApplicationRequestHandler.java
> +                throw new UncheckedServletException(e);
요거 Response 만들때마다 잡게 될거같은데 꼭 여기서 잡아야할까요 ?

2024-07-14 07:06 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/ApplicationRequestHandler.java
> +        return new Response(requestLine.getHttpProtocol(), HttpStatusCode.NOT_FOUND, ContentType.TEXT_HTML, StandardCharsets.UTF_8, "Hello World!".getBytes());
default가 Hello World!가 맞을까요 ? `/` 말고도 정의되지 않은 다른 경로들도 전부 Hello World!를 보여줄 것 같아요

2024-07-14 07:06 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/StaticResourceRequestHandler.java
> +            if (requestLine.pathEndsWith("500.html")) {
이 요청은 왜 따로 빠져있는걸까요 ?

2024-07-15 09:07 UTC, gutenLEE commented on tomcat/src/main/java/camp/nextstep/UserController.java
> +    public static ViewModel findUser(Map<String, Object> queryParamMap) {
정말 단순하게 나중에 미션 내용중에 DI이 있길래 그때 하려고 static으로 했습니다ㅎㅎ
일관성있게 UserService처럼 static 선언 없이 가겠습니다!

2024-07-15 11:30 UTC, gutenLEE reviewed
피드백 주신 부분들 반영했습니다!


이번 추가  작업에서는 `Http11Processor -> RequestMapping -> RequestHandler `의 협력 흐름에서 4xx 에러와 5xx 에러 처리를 분리하고자 했으나 깔끔하게 잘 되지 않았습니다ㅠ

2024-07-15 11:30 UTC, gutenLEE commented on tomcat/src/main/java/org/apache/coyote/http11/ApplicationRequestHandler.java
>              } catch (IOException | RuntimeException e) {
> 요거 Response 만들때마다 잡게 될거같은데 꼭 여기서 잡아야할까요 ? [(링크)](https://github.com/next-step/java-http/pull/37/files/2f1f37722a809f6da11d69b238c9a47ef6c07322#r1677048187)

이렇게 한 이유가 ApplicationRequestHandler가 요청을 위임한 객체가 처리 중 예외가 발생할 경우 
서버 에러를 반환하기 위해 이렇게 해보았습니다!

2024-07-15 11:38 UTC, gutenLEE commented on tomcat/src/main/java/org/apache/coyote/http11/StaticResourceRequestHandler.java
> +            if (requestLine.pathEndsWith("500.html")) {
```java
public final class RequestParser {

    public static RequestLine parse(InputStream inputStream, Charset charset)  {
        try {
            final var br = new BufferedReader(new InputStreamReader(inputStream, charset));
            final var readLine = br.readLine();
            return new RequestLine(readLine);
        } catch (IOException e) {
            throw new UncheckedServletException(e);
        } catch (HttpRequestLineInvalidException e) {
            return RequestLine.SERVER_ERROR_REQUEST_LINE;
        }
    }
}
```

리퀘스트 라인 파싱하다 예외가 발생할 경우 500.html 페이지를 반환하기 위한 예외처리 때문인데요, 
`RequestParser`가 `RequestLine.SERVER_ERROR_REQUEST_LINE` 반환하는게 
특정 상태의 `RequsetLine`을 알아야되서 결합도가 올라갔을까요?

`Http11Processor` try-catch에서 처리하려니 catch구문에서 OutputStream 변수에 접근할 수 없어서 
이런 구조가 나와버렸습니다 ㅠ
`HttpProcessor`와 `RequestParser`, `RequestHandler` 사이에 객체를 하나 더 둘까 고민했는데
지금은 과한거같아서 보류했습니다!

```java
    @Override
    public void process(final Socket connection) {
        try (final var inputStream = connection.getInputStream();
             final var outputStream = connection.getOutputStream()) {

            final var requestLine = RequestParser.parse(inputStream, StandardCharsets.UTF_8);
            final var requestMapping = new RequestMapping();
            final var handler = requestMapping.getHandler(requestLine);

            final var response = handler.service(requestLine);

            outputStream.write(response.generateMessage().getBytes());
            outputStream.flush();
        } catch (IOException | UncheckedServletException e) {
            log.error(e.getMessage(), e);
        }
    }
```

2024-07-15 17:23 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/StaticResourceRequestHandler.java
> +            if (requestLine.pathEndsWith("500.html")) {
파싱하다 예외가 발생하면 그건 그거대로 500 응답을 주고, 그럴 경우 클라이언트 판단 하에 에러페이지를 요청하던가 하면 될 것 같아요! 만약 json 타입으로 요청이 왔는데 파싱이 잘못되거나 서버 에러로 500.html을 응답하면 제대로 처리 할 수 있을까요 ?

2024-07-15 17:24 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/StaticResourceRequestHandler.java
> +            if (requestLine.pathEndsWith("500.html")) {
뭔가 구조적인 문제라기보단 플로우가 안맞는거같아서 여쭤봤어요! 그리고 저런 논리라면 나머지 에러페이지도 경우에 따라 응답을 줘야될텐데 그런 처리는 또 없어보여서요!

2024-07-15 17:26 UTC, shared-moon commented on tomcat/src/main/java/org/apache/coyote/http11/ApplicationRequestHandler.java
>              } catch (IOException | RuntimeException e) {
Response 생성 부분을 따로 빼거나 해서 예외처리를 몰아두면 좋을 것 같아서 말씀드렸었어요!

2024-07-15 17:28 UTC, shared-moon approved these changes
유희님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
질문 남겨주신데 코멘트를 달아 뒀는데요, 나머지 내용은 다음 미션 진행 하시면서 반영해보면 좋을 것 같아요
이번 PR은 머지 하도록 할게요
고생 많으셨습니다!

2024-07-15 17:28 UTC, merged

2024-07-16 04:21 UTC, gutenLEE commented on tomcat/src/main/java/org/apache/coyote/http11/StaticResourceRequestHandler.java
> +            if (requestLine.pathEndsWith("500.html")) {
> 파싱하다 예외가 발생하면 그건 그거대로 500 응답을 주고, 그럴 경우 클라이언트 판단 하에 에러페이지를 요청하던가 하면 될 것 같아요! 만약 json 타입으로 요청이 왔는데 파싱이 잘못되거나 서버 에러로 500.html을 응답하면 제대로 처리 할 수 있을까요 ?

아 생각을 못했네요 감사합니다!